repos:
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
    - id: gitleaks
      name: Detect hardcoded secrets
      description: Detect hardcoded secrets using Gitleaks
      entry: gitleaks protect --config=".gitleaks.toml" --verbose --redact --staged
      pass_filenames: false
